---
title: "HI_quantity_quality"
author: "Erin Campbell"
date: "12/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r automated}
LENA_counts <- read_csv("/Volumes/pn-opus/VIHI/Scripts/LENA_Scripts/data/VIHI_its_details.csv") %>%
  filter(group == "HI" | group == "TD")


compare_AWC <- wilcox.test(LENA_counts$AWC ~ LENA_counts$group)
AWC_plot <-
  ggplot(data = LENA_counts, aes(
    x = group,
    y = AWC,
    color = group,
    fill = group)) +
  geom_violin(alpha = .5, trim = FALSE) +
  geom_jitter(width = 0.2, height = 0) +
  theme_classic() +
  labs(y = "Adult Word Count", x = NULL, element_text(size = 14)) +
  theme(
    legend.title = element_blank(),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  scale_fill_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  stat_summary(
    fun = mean,
    geom = "point",
    color = 'black',
    alpha = 0.8) +
  geom_linerange(aes(
    ymin = (mean(AWC) - std.error(AWC)),
    ymax = (mean(AWC) - std.error(AWC)))) +
  stat_summary(fun.data = "mean_cl_boot", color = 'black') +
  scale_x_discrete(
    labels = c(
      "HI" = "Cochlear Implant",
      "TD" = "Typically-Hearing")) +
  coord_cartesian(ylim = c(0, (max(LENA_counts$AWC * 1.1)))) +
  theme( axis.text = element_text(size = 14),
    axis.title.y = element_text(size = 18),
    strip.text.x = element_text(size = 14)) 
AWC_plot



compare_CTC <- wilcox.test(LENA_counts$CTC ~ LENA_counts$group)
CTC_plot <-
  ggplot(data = LENA_counts, aes(
    x = group,
    y = CTC,
    color = group,
    fill = group)) +
  geom_violin(alpha = .5, trim = FALSE) +
  geom_jitter(width = 0.2, height = 0) +
  theme_classic() +
  labs(y = "Conversational Turn Count", x = NULL, element_text(size = 14)) +
  theme(
    legend.title = element_blank(),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  scale_fill_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  stat_summary(
    fun = mean,
    geom = "point",
    color = 'black',
    alpha = 0.8) +
  geom_linerange(aes(
    ymin = (mean(CTC) - std.error(CTC)),
    ymax = (mean(CTC) - std.error(CTC)))) +
  stat_summary(fun.data = "mean_cl_boot", color = 'black') +
  scale_x_discrete(
    labels = c(
      "HI" = "Cochlear Implant",
      "TD" = "Typically-Hearing")) +
  coord_cartesian(ylim = c(0, (max(LENA_counts$CTC * 1.1)))) +
  theme( axis.text = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    strip.text.x = element_text(size = 14)) 
CTC_plot
```
```{r load-transcripts}
#read in data that has been mass exported via ELAN; add informative column names

single_column_with_names <- read_delim("/Volumes/pn-opus/VIHI/WorkingFiles/fake_VI_Oct19.txt", 
     delim = "\t", escape_double = FALSE, 
     trim_ws = TRUE,col_names = FALSE) %>%
  rename(tier=X1,
         participant=X2,
         onset_ms=X3,
         offset_ms=X4,
         duration=X5,
         utterance=X6,
         filename=X7,
         filepath=X8)

#wrangle data so that each utterance has a single row, all participant labels appear in a single column, all utterance transcriptions in a single column, xds annotations appear in a single column, all PI annotations appear in a single column)
wide_transcripts <- pivot_wider(single_column_with_names, names_from = "tier", values_from = "utterance") %>%
  unite("xds", contains("xds@"), remove = TRUE, na.rm = TRUE) %>%
  unite("PI", contains("PI"), remove = TRUE, na.rm = TRUE) %>%
  unite("utterance", c("CHI","UC1","FA1", "FA2", "FA3","FA4","FA5", "FA6", "FA7", "FA8", "FA9", "F10", "FAE", "MA1", "MA2","MA3", "MC1", "FC1", "FC2", "EE1"), remove = TRUE, na.rm = TRUE) %>%
  mutate(VIHI_ID = str_sub(filename, 1,10))

```

```{r transcripts-to-words}

# # find + list all LENA transcripts on pn-opus
LENA_files <- list.files("/Volumes/pn-opus/VIHI/SubjectFiles/LENA", pattern="*_lena.txt", full.names=TRUE, recursive = TRUE)

# # read in LENA transcripts
# # ek2ec, suggestion: readr::read_delim should be able to read a list of files. If you have an older readr version that can't do that, another options is to use `map_dfr`.
# VIHI_LENA_transcripts <- data.frame() # create an empty dataframe
# for (filename in LENA_files) {
#   #for each file found
#   print(filename) #print which one we're working on
#   new <-
#     read_delim(
#       filename,
#       "\t",
#       escape_double = FALSE,
#       col_names = FALSE,
#       trim_ws = TRUE,
#       col_types = cols(.default = "c")
#     ) %>% #read in file
#     
#     mutate(VIHI_ID = str_sub(filename, -19,-10),
#            group = str_sub(VIHI_ID, 1, 2)) # using the filepath, create column with subject ID and column with group
#   VIHI_LENA_transcripts <-
#     bind_rows(VIHI_LENA_transcripts, new) #bind this to the (formerly) empty dataframe
# }
# 
# VIHI_LENA_transcripts <-
#   VIHI_LENA_transcripts %>% 
#   dplyr::rename(
#     Speaker = X1,
#     OnsetTime = X2,
#     OffsetTime = X3,
#     Duration = X4,
#     Utterance = X5,
#     Addressee = X6
#   ) %>%
#   filter(Speaker != 'CHI') #filter out child utterances, since we're only interested in input
# 



all_lena <- read_delim("data/all_lena.txt", 
    delim = "\t", escape_double = FALSE, 
    col_names = FALSE, trim_ws = TRUE) %>%
  dplyr::rename(
    Speaker = X1,
    OnsetTime = X2,
    OffsetTime = X3,
    Duration = X4,
    Utterance = X5,
    filename = X6,
    filepath = X7,
    
  )   %>%
  mutate(VIHI_ID = str_sub(filename, 1,10),
         group = as.factor(str_sub(filename, 1,2)))%>%
  filter(Speaker != 'CHI' & Speaker != 'code' & Speaker != 'sampling_type')

VIHI_LENA_utterances <- all_lena %>%
   mutate(utterance_clean = str_remove_all(Utterance, pattern = ("\\[.*?<>"))) %>%
  separate(utterance_clean,
           into = paste0("Word", 1:46),
           sep = " ") #separate utterances into columns with 1 column per word

VIHI_LENA_words <- VIHI_LENA_utterances %>%
  mutate(uttnum = seq(1, nrow(VIHI_LENA_utterances), 1)) %>% #give each utterance a unique number
  pivot_longer(cols = Word1:Word46,
               #pivot the word columns into a single Word column
               names_to = "utt_loc",
               #create another column that gives the location within utterance (ex:Word2)
               values_to = "Word") %>%
  dplyr::select(VIHI_ID, group, uttnum, utt_loc, Word) %>%
  filter(!is.na(Word)) %>% #filter out blank rows
  left_join(lancaster_norms) %>% # join with lancaster norms
  filter(!is.na(Auditory.mean)) %>%
  dplyr::select(Word,
         VIHI_ID,
         group,
         Auditory.mean:Dominant.sensorimotor,
         utt_loc,
         uttnum) #remove unwanted columns

manual_word_types <- VIHI_LENA_words %>% 
  group_by(VIHI_ID) %>%
  distinct(Word, .keep_all=TRUE) %>%
  summarise(types = n())
manual_word_tokens <- VIHI_LENA_words %>% 
  group_by(VIHI_ID) %>%
  summarise(tokens = n())
manual_word_TTR <- manual_word_types %>% left_join(manual_word_tokens) %>%
  mutate(TTR = types/tokens,
         group = as.factor(str_sub(VIHI_ID, 1,2)))  %>%
  filter(group!="VI")



TTR_plot <-  ggplot(data = (manual_word_TTR %>% filter(group!="VI")), aes(
    x = group,
    y = TTR,
    color = group,
    fill = group)) +
  geom_violin(alpha = .5, trim = FALSE) +
  geom_jitter(width = 0.2, height = 0) +
  theme_classic() +
  labs(y = "Unique Words /\nTotal Words", x = NULL, element_text(size = 14)) +
  theme(
    legend.title = element_blank(),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  scale_fill_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  stat_summary(
    fun = mean,
    geom = "point",
    color = 'black',
    alpha = 0.8) +
  geom_linerange(aes(
    ymin = (mean(TTR) - std.error(TTR)),
    ymax = (mean(TTR) - std.error(TTR)))) +
  stat_summary(fun.data = "mean_cl_boot", color = 'black') +
  scale_x_discrete(
    labels = c(
      "HI" = "Cochlear Implant",
      "TD" = "Typically-Hearing")) +
  coord_cartesian(ylim = c(0, (max(manual_word_TTR$TTR * 1.1)))) +
  theme( axis.text = element_text(size = 14),
    axis.title.y = element_text(size = 18),
    strip.text.x = element_text(size = 14)) 
TTR_plot

t.test(manual_word_TTR$TTR~manual_word_TTR$group)



manual_word_count_plot <-  ggplot(data = (manual_word_TTR %>% filter(group!="VI")), aes(
    x = group,
    y = tokens,
    color = group,
    fill = group)) +
  geom_violin(alpha = .5, trim = FALSE) +
  geom_jitter(width = 0.2, height = 0) +
  theme_classic() +
  labs(y = "Manual Word Counts", x = NULL, element_text(size = 14)) +
  theme(
    legend.title = element_blank(),
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  scale_fill_manual(
    breaks = c("TD", "HI"),
    labels = c("Typically-Hearing", "Cochlear Implant"),
    values = c("#b16fff", "#FFACE4")) +
  stat_summary(
    fun = mean,
    geom = "point",
    color = 'black',
    alpha = 0.8) +
  geom_linerange(aes(
    ymin = (mean(tokens) - std.error(tokens)),
    ymax = (mean(tokens) - std.error(tokens)))) +
  stat_summary(fun.data = "mean_cl_boot", color = 'black') +
  scale_x_discrete(
    labels = c(
      "HI" = "Cochlear Implant",
      "TD" = "Typically-Hearing")) +
  coord_cartesian(ylim = c(0, (max(manual_word_TTR$tokens * 1.1)))) +
  theme( axis.text = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    strip.text.x = element_text(size = 14)) 
manual_word_count_plot
t.test(manual_word_TTR$tokens~manual_word_TTR$group)


```



```{r sensory-words}
sensory_words <- VIHI_LENA_words %>% 
  filter(group!="VI") %>%
  anti_join(stop_words, by= c("Word" = "word"))

sensory_words_totals <- sensory_words %>% 
   filter(!is.na(Dominant.perceptual)) %>%
   group_by(group, VIHI_ID) %>%
  summarise(total = n()) 

sensory_words_by_modality_long <- sensory_words%>% 
  group_by(group, VIHI_ID, Dominant.perceptual) %>%
  summarise(by_modality = n()) %>%
  left_join(sensory_words_totals) %>%
  mutate(by_modality = replace_na(by_modality,0),
         prop = by_modality/total)
sensory_words_by_modality_wide <- sensory_words_by_modality_long%>% 
  pivot_wider(names_from = Dominant.perceptual, values_from=prop)%>%
  left_join(sensory_words_by_modality_long)

ggplot((sensory_words_by_modality_long %>% group_by(group, Dominant.perceptual) %>% summarise(mean_prop=mean(prop))), aes(fill = Dominant.perceptual, y= mean_prop, x = group)) +
  geom_bar(position = "stack", stat = "identity")  +
  geom_text(aes(label=round(mean_prop,2)), position=position_stack(vjust=0.5)) +
  xlab("Group") + 
  ylab ("Proportion of words by sensory modality") +
  theme_classic()+
  theme(text=element_text(size=10)) + scale_x_discrete(labels=c("HI" = "Cochlear Implant", "TD" = "Typically-Hearing"))
```

```{r mlu}
real_utts_only <- VIHI_LENA_utterances %>%
  filter(Speaker !="EE1" & Speaker !="CHI")

all_lena <- read_delim("data/all_lena_with_xds.txt", 
    delim = "\t", escape_double = FALSE, 
    col_names = TRUE, trim_ws = TRUE) %>%
  dplyr::select(-c(CHI,EE1)) %>%
  unite("xds", contains("xds@"), remove = TRUE, na.rm = TRUE)%>%
  unite("utterance", c("UC1","FA1", "FA2", "FA3","FA4","FA5", "FA6", "FA7", "FA8", "FA9", "F10", "FAE", "MA1", "MA2","MA3", "MC1", "FC1", "FC2", "UC2", "UC3", "MA4", "MA5", "MA6", "MA7", "UC4", "UC5", "UC6", "UC7", "MC2", "MAE", "UCI"), remove = TRUE, na.rm = TRUE) %>%
  mutate(VIHI_ID = str_sub(File, 1,10),
         group = as.factor(str_sub(VIHI_ID, 1,2)))


tokenized_utterances <- morphemepiece_tokenize(all_lena$utterance, vocab = morphemepiece_vocab(),
      lookup = morphemepiece_lookup(),
      unk_token = "[UNK]",
      max_chars = 100)

df_tokenized_utterances <- tokenized_utterances %>%
  plyr::ldply(rbind)
  
df_morphemes_utterances<- data.frame(ifelse(is.na(df_tokenized_utterances),0,1))
df_morphemes_utterances$morphemecount<-rowSums(df_morphemes_utterances)
all_lena$morphemecount<-df_morphemes_utterances$morphemecount 
all_lena <- all_lena %>%
  filter(morphemecount >0)
```


```{r mlu-and-xds}


VIHI_LENA_utterances <- all_lena %>%
   mutate(utterance_clean = str_remove_all(Utterance, pattern = ("\\[.*?<>"))) %>%
  separate(utterance_clean,
           into = paste0("Word", 1:46),
           sep = " ") #separate utterances into columns with 1 column per word

VIHI_LENA_words <- VIHI_LENA_utterances %>%
  mutate(uttnum = seq(1, nrow(VIHI_LENA_utterances), 1)) %>% #give each utterance a unique number
  pivot_longer(cols = Word1:Word46,
               #pivot the word columns into a single Word column
               names_to = "utt_loc",
               #create another column that gives the location within utterance (ex:Word2)
               values_to = "Word") %>%
  select(VIHI_ID, group, uttnum, utt_loc, Word) %>%
  filter(!is.na(Word)) %>% #filter out blank rows
  left_join(lancaster_norms) %>% # join with lancaster norms
  filter(!is.na(Auditory.mean)) %>%
  select(Word,
         VIHI_ID,
         group,
         Auditory.mean:Dominant.sensorimotor,
         utt_loc,
         uttnum) #remove unwanted columns
```

```{r xds}
xds_props_totals <- all_lena %>% 
  filter(xds %in% c("C","A","B","P", "O", "U")) %>%
  group_by(VIHI_ID, group) %>%
  summarise(total_counts=n()) 

xds_props <- all_lena %>%
  group_by(VIHI_ID, group, xds) %>%
  summarise(xds_counts=n()) %>%
  filter(group!="VI") %>%
  left_join(xds_props_totals) %>%
  mutate(xds_props = xds_counts/total_counts) %>%
  group_by(group,xds) %>%
  summarise(group_props = mean(xds_props, na.rm=TRUE)) %>%
  filter(xds!="")

cds_props <- all_lena %>%
  group_by(VIHI_ID, group, xds) %>%
  summarise(xds_counts=n()) %>%
  filter(group!="VI") %>%
  left_join(xds_props_totals) %>%
  mutate(xds_props = xds_counts/total_counts) %>%
  filter(xds=="C")
cds_compare <- t.test(cds_props$xds_props ~ cds_props$group)

ggplot(xds_props, aes(fill = xds, y= group_props, x = group)) +
  geom_bar(position = "stack", stat = "identity")  +
  geom_text(aes(label=round(group_props,2)), position = position_stack(vjust=.5))+
  xlab("Group") + 
  ylab ("Proportion, by number of utterances") +
  scale_fill_discrete(labels=c('Adult-directed', 'Both child and adult', 'Child-directed', 'Other', 'Pet-directed', 'Unsure'), name="Addressee")+
  theme_classic()+
  theme(text=element_text(size=10)) + 
  scale_x_discrete(labels=c("HI" = "Cochlear Implant", "TD" = "Typically-Hearing"))
  
  
  geom_text(aes(label=case_when(xds_props>.03~xds_props,TRUE~" ")), position=position_stack(vjust=0.5)) +

```
