---
title: "VI LENA Supplement"
author: "Erin Campbell"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r libraries-and-data, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library(tidyverse)
library(ggplot2)
library(broom)
library(papaja)
library(knitr)
library(kableExtra)

# quantity
LENA_counts <- read_csv("./data/LENA/Automated/LENA_counts.csv")
manual_word_tokens <- read_csv("./data/LENA/Transcripts/Derived/manual_word_tokens.csv")
VITD_transcripts <- read_csv("./data/LENA/Transcripts/Derived/VITD_transcripts.csv")
VITD_LENA_words <- read_csv("./data/LENA/Transcripts/Derived/VITD_LENA_words.csv")
# interactive
xds_props <- read_csv("./data/LENA/Transcripts/Derived/xds_props.csv")
xds_props_wide <- read_csv("./data/LENA/Transcripts/Derived/xds_props_wide.csv")
# linguistic
MLUs <- read_csv("./data/LENA/Transcripts/Derived/MLUs.csv")
MLU_subset_for_agreement <- read_csv("./data/LENA/Transcripts/Derived/MLU_subset_for_agreement.csv")
TTR_calculations <- read_csv("./data/LENA/Transcripts/Derived/TTR_calculations.csv")
raw_TTR_calculations <- read_csv("./data/LENA/Transcripts/Derived/TTR_calculations.csv")
# conceptual
sensory_props <- read_csv("./data/LENA/Transcripts/Derived/sensory_props.csv")
sensory_props_wide <- read_csv("./data/LENA/Transcripts/Derived/sensory_props_wide.csv")
temporality_props <- read_csv("./data/LENA/Transcripts/Derived/temporality_props.csv")
temporality_props_wide <- read_csv("./data/LENA/Transcripts/Derived/temporality_props_wide.csv")
content_words_only <- read_csv("./data/LENA/Transcripts/Derived/content_words_only.csv")
verbs_only <- read_csv("./data/LENA/Transcripts/Derived/verbs_only.csv")

VI_matches_demo <- read_csv("./data/Demographics/VI_matches_demo.csv", na = c("", "NA", " "))


```


# Equivalence Testing

```{r equivalence-tests, echo=TRUE}
# Adult Word Count: d=0.3
TOSTER::t_TOST(AWC_per_hour ~ group, data = LENA_counts, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .3, eqbound_type = "SMD", alpha = .05)
# Adult Word Count: d=0.5
TOSTER::t_TOST(AWC_per_hour ~ group, data = LENA_counts, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .5, eqbound_type = "SMD", alpha = .05)
# Adult Word Count: d=0.7
TOSTER::t_TOST(AWC_per_hour ~ group, data = LENA_counts, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD", alpha = .05)

# Manual Word Count: d=0.3
TOSTER::t_TOST(MWC_per_hour ~ group, data = manual_word_tokens, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .3, eqbound_type = "SMD",alpha = .05)
# Manual Word Count: d=0.5
TOSTER::t_TOST(MWC_per_hour ~ group, data = manual_word_tokens, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .5, eqbound_type = "SMD",alpha = .05)
# Manual Word Count: d=0.7
TOSTER::t_TOST(MWC_per_hour ~ group, data = manual_word_tokens, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD",alpha = .05)


# Conversational Turn Count: d=0.3
TOSTER::t_TOST(CTC_per_hour ~ group, data = LENA_counts, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .3, eqbound_type = "SMD",alpha = .05)
# Conversational Turn Count: d=0.5
TOSTER::t_TOST(CTC_per_hour ~ group, data = LENA_counts, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .5, eqbound_type = "SMD",alpha = .05)
# Conversational Turn Count: d=0.7
TOSTER::t_TOST(CTC_per_hour ~ group, data = LENA_counts, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD",alpha = .05)


# Proportion of Child-Directed Speech: d=0.3
TOSTER::t_TOST(prop_CDS ~ group, data = xds_props_wide, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .3, eqbound_type = "SMD", alpha = .05)
# Proportion of Child-Directed Speech: d=0.5
TOSTER::t_TOST(prop_CDS ~ group, data = xds_props_wide, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .5, eqbound_type = "SMD", alpha = .05)
# Proportion of Child-Directed Speech: d=0.7
TOSTER::t_TOST(prop_CDS ~ group, data = xds_props_wide, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD", alpha = .05)


# Type-Token Ratio: d=0.3
TOSTER::t_TOST(mean_ttr ~ group, data = TTR_calculations, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .3, eqbound_type = "SMD",alpha = .05)
# Type-Token Ratio: d=0.5
TOSTER::t_TOST(mean_ttr ~ group, data = TTR_calculations, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .5, eqbound_type = "SMD",alpha = .05)
# Type-Token Ratio: d=0.7
TOSTER::t_TOST(mean_ttr ~ group, data = TTR_calculations, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD",alpha = .05)

# Proportion of Highly Visual Words: d=0.3
TOSTER::t_TOST(prop_Visual ~ group, data = sensory_props_wide, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD", alpha = .05)
# Proportion of Highly Visual Words: d=0.5
TOSTER::t_TOST(prop_Visual ~ group, data = sensory_props_wide, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD", alpha = .05)
# Proportion of Highly Visual Words, d=0.7
TOSTER::t_TOST(prop_Visual ~ group, data = sensory_props_wide, hypothesis = "EQU", paired = TRUE, 
               var.equal = TRUE, eqb = .7, eqbound_type = "SMD", alpha = .05)

```

# Age Interactions

```{r age-differences, include=FALSE}
LENA_agediffs <- LENA_counts %>%
  left_join(VI_matches_demo %>% select(Age_months, VIHI_ID)) %>%
  mutate(group = as.factor(case_when(group == "VI" ~ "Blind",
                   group == "TD" ~ "Sighted")),
         group = fct_relevel(group, "Sighted"))
AWC_agediffs_model <- lm(AWC_per_hour ~ group*Age_months, data = LENA_agediffs)
CTC_agediffs_model <- lm(CTC_per_hour ~ group*Age_months, data = LENA_agediffs)

MWC_agediffs <- manual_word_tokens %>% 
  left_join(VI_matches_demo %>% select(Age_months, VIHI_ID)) %>%
  mutate(group = as.factor(case_when(group == "VI" ~ "Blind",
                   group == "TD" ~ "Sighted")),
         group = fct_relevel(group, "Sighted"))
MWC_agediffs_model <- lm(MWC_per_hour ~ group*Age_months, data = MWC_agediffs)

xds_agediffs <- xds_props_wide %>%
  left_join(VI_matches_demo %>% select(Age_months, VIHI_ID))  %>%
  mutate(group = as.factor(case_when(group == "VI" ~ "Blind",
                   group == "TD" ~ "Sighted")),
         group = fct_relevel(group, "Sighted"))
CDS_agediffs_model <- lm(prop_CDS ~ group*Age_months, data = xds_agediffs)

TTR_agediffs <- TTR_calculations %>%
  left_join(VI_matches_demo %>% select(Age_months, VIHI_ID))  %>%
  mutate(group = as.factor(case_when(group == "VI" ~ "Blind",
                   group == "TD" ~ "Sighted")),
         group = fct_relevel(group, "Sighted"))
TTR_agediffs_model <- lm(mean_ttr ~ group*Age_months, data = TTR_agediffs)

MLU_agediffs <- MLUs %>% 
  left_join(VI_matches_demo %>% select(Age_months, VIHI_ID))  %>%
  mutate(group = as.factor(case_when(group == "VI" ~ "Blind",
                   group == "TD" ~ "Sighted")),
         group = fct_relevel(group, "Sighted"))
MLU_agediffs_model <- lm(MLU ~ group*Age_months, data = MLU_agediffs)

temporality_agediffs <- temporality_props %>%
  filter(verb_temporality == "displaced") %>%
  left_join(VI_matches_demo %>% select(Age_months, VIHI_ID))  %>%
  mutate(group = as.factor(case_when(group == "VI" ~ "Blind",
                   group == "TD" ~ "Sighted")),
         group = fct_relevel(group, "Sighted"))
temporality_agediffs_model <- lm(prop ~ group*Age_months, data = temporality_agediffs)

visual_agediffs <- sensory_props %>%
  left_join(VI_matches_demo %>% select(Age_months, VIHI_ID)) %>%
  mutate(group = as.factor(case_when(group == "VI" ~ "Blind",
                   group == "TD" ~ "Sighted")),
         group = fct_relevel(group, "Sighted"))
summary(lm(prop ~ Modality*group*Age_months, data = visual_agediffs))
sensory_agediffs_model <- lm(prop ~ Modality*group*Age_months, data = visual_agediffs)


```

## Quantity

```{r awc}
ggplot(LENA_agediffs, aes(x = Age_months, y=AWC_per_hour, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Adult Word Count (per hour)")


AWC_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()

```

```{r mwc}
ggplot(MWC_agediffs, aes(x = Age_months, y=MWC_per_hour, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Manual Word Count (per hour)")


MWC_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()
```

## Interaction

```{r ctc}
ggplot(LENA_agediffs, aes(x = Age_months, y=CTC_per_hour, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Conversational Turn Count (per hour)")

CTC_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()
```

```{r cds}
ggplot(xds_agediffs, aes(x = Age_months, y=prop_CDS, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Proportion of Child-Directed Speech")

CDS_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()

```

## Linguistic

```{r ttr}
ggplot(TTR_agediffs, aes(x = Age_months, y=mean_ttr, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Type-Token Ratio")

TTR_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()
```

```{r mlu}
ggplot(MLU_agediffs, aes(x = Age_months, y=MLU, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Mean Length of Utterance\n(Morphemes)")

MLU_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()
```

## Conceptual

```{r lancaster, fig.height=8}
ggplot(visual_agediffs, aes(x = Age_months, y=prop, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Proportion of Content Words") +
  facet_wrap(.~Modality, scales = "free", nrow = 4)

sensory_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()

```

```{r displaced}
ggplot(temporality_agediffs, aes(x = Age_months, y=prop, color=group,fill=group)) +
  geom_point() +
  geom_smooth(method="lm") +
    scale_color_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
    scale_fill_manual(
      breaks = c("Sighted", "Blind"),
      labels = c("Sighted", "Blind"),
      values = c("#b16fff", "#ade7f5")
    ) +
  theme_classic() +
  xlab("Age (months)") +
  ylab("Proportion of Temporally Displaced Verbs")

temporality_agediffs_model %>%
  tidy() %>%
  mutate(estimate = print_num(estimate),
         std.error = print_num(std.error),
         statistic = print_num(statistic),
         p.value = print_p(p.value)) %>%
  kable()
```
